### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'all.geojson'

### ISSUE THREAD

**Issue by ghost** [AshKyd/geojson-regions#11]
When running `./go.sh`, it throws following error:

```
Error: ENOENT: no such file or directory, open 'all.geojson'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
```

I found that in `go.sh` file, the `rm` command deletes the file. I think all.geojson should be kept somewhere else as it is a reference to generate rest of the files.

**Comment by ghost** [comment]
Found the issue. I ran the script without installing `gdal`...

Keeping this issue here as it might help someone else...

**Comment by AshKyd** [comment]
Thanks, that's good to know!
