### ISSUE TITLE
Problem with loading the geojson information for some of the countries

### ISSUE THREAD

**Issue by RT100** [AshKyd/geojson-regions#3]
Hi 
Thanks for your time and contribution to this amazing library. 
Today, I downloaded the latest geojson file for Europe using the the tool on "https://geojson-maps.ash.ms/" and I noticed that the geojson regions for the following countries are not loaded in my application: Denmark,United Kingdom,France, Netherlands
I took a look at  the "geojson-regions/countries/10m/index.json" file and searched for the Denmark entry which seems to be referring to the "DN1.geojson" file which actually represents Greenland.
Regards

**Comment by mmintel** [comment]
Any updates on this?

**Comment by AshKyd** [comment]
Thanks folks, completely missed these. Will work on a fix over the next couple of days.

**Comment by AshKyd** [comment]
The problem is that the script is using the `sov_a3` field as a unique identifier, but the field is not unique. Replacing this with `iso_a3` and falling back to country name for those without an a3 code should fix this. I'm working on a solution.

**Comment by marc-ed-raffalli** [comment]
Hi, any updates on this ?
USA, China, Australia also seem to be missing
Fantastic work by the way !

**Comment by AshKyd** [comment]
This should be fixed now, please let me know if there are any more issues.

**Comment by marc-ed-raffalli** [comment]
Thanks for the quick fix. I cannot access the page, it says `Your connection is not private`

**Comment by AshKyd** [comment]
Ah, my bad, messed up TLS. Should be good now.

**Comment by marc-ed-raffalli** [comment]
Looks good !
