### ISSUE TITLE
In Firefox Africa checkbox is missing

### ISSUE THREAD

**Issue by phocks** [AshKyd/geojson-regions#9]
Comes and goes as you resize browser.

![snip20170817_3](https://user-images.githubusercontent.com/437566/29389417-4af03c44-832d-11e7-96d3-43452342427e.png)

**Comment by AshKyd** [comment]
This is really weird. It looks like a Firefox bug, cos the checkbox reappears when I hover it in the devtools.

Someone should really do a test case and submit it to them as a Gecko bug. I'm sleepy and/or zonked after work, but maybe l8r.
